name: Test & Deploy
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test -- --browsers=ChromeHeadless --watch=false

  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --auth "${{ secrets.NETLIFY_ACCESS_TOKEN }}" --dir=dist/nim-angular
